#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import rasterio

__license__ = "Apache License, Version 2.0"
__author__     = "Soeren Gebbert"
__copyright__  = "Copyright 2018, Soeren Gebbert"
__maintainer__ = "Soeren Gebbert"
__email__      = "soerengebbert@googlemail.com"


def main():

    parser = argparse.ArgumentParser(description='Execute an UDF on the provided data')

    parser.add_argument("raster_inputs", type=str, required=True,
                        help="Raster files. If several raster files are provided, then each raster file must have"
                             "the same number of bands.")

    parser.add_argument("raster_output_dir", type=str, required=True,
                        help="The output directory to store the computed results.")

    parser.add_argument("path_to_udf", type=str, required=True,
                        help="The UDF file to execute.")

    args = parser.parse_args()


if __name__ == '__main__':
    main()
