#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import uvicorn
from openeo_udf.server.app import app
from openeo_udf.server.tools import create_storage_directory

__license__ = "Apache License, Version 2.0"
__author__     = "Soeren Gebbert"
__copyright__  = "Copyright 2018, Soeren Gebbert"
__maintainer__ = "Soeren Gebbert"
__email__      = "soerengebbert@googlemail.com"


def main():

    parser = argparse.ArgumentParser(description='Start udf server')

    parser.add_argument("--host", type=str, required=False, default="0.0.0.0",
                        help="The IP address that should be used for the server")

    parser.add_argument("--port", type=int, required=False, default=5000,
                        help="The port that should be used for the server")

    parser.add_argument("--log_level", type=str, required=False, default="info",
                        help="Set the log level of the uvicorn server")

    args = parser.parse_args()

    create_storage_directory()
    uvicorn.run(app, host=args.host, port=args.port, log_level=args.log_level, reload=True)


if __name__ == '__main__':
    main()
